# Generated by Django 4.1.7 on 2023-03-06 15:06

import contract.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=250, null=True)),
                ('sector', models.CharField(blank=True, max_length=250, null=True)),
                ('project', models.CharField(blank=True, max_length=250, null=True)),
                ('works_type', models.CharField(max_length=250)),
                ('contract_type', models.CharField(choices=[('توريد + تنفيذ', 'توريد + تنفيذ'), ('توريد', 'توريد'), ('تنفيذ', 'تنفيذ')], max_length=250)),
                ('contract_value', models.IntegerField()),
                ('contract_duration', models.IntegerField()),
                ('cost_istimation', models.CharField(choices=[('إنشاءات (أ)', 'إنشاءات (أ)'), ('بنية تحتية (ج)', 'بنية تحتية (ج)')], max_length=250)),
                ('secondParty_name', models.CharField(max_length=250)),
                ('bank_account', models.IntegerField()),
                ('iban', models.IntegerField()),
                ('tax_number', models.IntegerField()),
                ('signature_authorization', models.FileField(null=True, upload_to='files')),
                ('delegated_nam', models.CharField(max_length=250)),
                ('delegated_title', models.CharField(max_length=250)),
                ('gov_id_no', models.CharField(max_length=250)),
                ('second_party_representative', models.CharField(max_length=250)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('commercial_register', models.FileField(upload_to='files')),
                ('commercial_register_date', models.DateField(validators=[contract.models.validate_rc])),
                ('establishment_company', models.CharField(choices=[('مؤسسة', 'مؤسسة'), ('شركة', 'شركة')], max_length=250)),
                ('association_contract', models.FileField(blank=True, null=True, upload_to='files')),
                ('zakat_Income_certificate', models.FileField(blank=True, null=True, upload_to='files')),
                ('sub_contractor_profile', models.FileField(blank=True, null=True, upload_to='files')),
                ('project_original_contract_quantities_table_copy', models.FileField(blank=True, null=True, upload_to='files')),
                ('contract_quantities_table', models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
                ('special_conditions', models.TextField()),
                ('payment_terms', models.TextField()),
            ],
            options={
                'verbose_name': 'Contract_Detail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TCTA_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'TCTA_action',
            },
        ),
        migrations.CreateModel(
            name='Sector_manager_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول'), ('رفض', 'رفض')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Sector_manager_action',
            },
        ),
        migrations.CreateModel(
            name='Financial_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Financial_action',
            },
        ),
        migrations.CreateModel(
            name='EVP_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'EVP_action',
            },
        ),
        migrations.CreateModel(
            name='Cost_estimation_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Cost_estimation_action',
            },
        ),
        migrations.CreateModel(
            name='Copy_contract_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Copy_contract_action',
            },
        ),
        migrations.CreateModel(
            name='Check_data_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Check_data_action',
            },
        ),
        migrations.CreateModel(
            name='Check_contract_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Check_contract_action',
            },
        ),
        migrations.CreateModel(
            name='CEO_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('قبول', 'قبول')], max_length=250, null=True)),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'CEO_action',
            },
        ),
        migrations.CreateModel(
            name='AssignAttach2_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('تم', 'تم')], max_length=250, null=True)),
                ('action_file', models.FileField(upload_to='files')),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'AssignAttach2_action',
            },
        ),
        migrations.CreateModel(
            name='AssignAttach1_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('تم', 'تم')], max_length=250, null=True)),
                ('action_file', models.FileField(upload_to='files')),
                ('action_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'AssignAttach1_action',
            },
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_creator', models.CharField(blank=True, max_length=250, null=True)),
                ('action_notes', models.TextField(max_length=250)),
                ('action_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('action_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('request_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actions', to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Action',
                'ordering': ['action_date'],
            },
        ),
    ]
