# Generated by Django 4.1.7 on 2023-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_remove_contract_detail_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignattach1_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignattach2_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ceo_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check_contract_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check_data_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copy_contract_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost_estimation_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evp_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector_manager_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcta_action',
            name='action_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
