# Generated by Django 4.1.7 on 2023-03-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_assignattach1_action_action_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignattach1_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assignattach2_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ceo_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='check_contract_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='check_data_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cost_estimation_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='evp_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='financial_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sector_manager_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tcta_action',
            name='action_creator',
            field=models.CharField(max_length=250),
        ),
    ]
