# Generated by Django 4.1.7 on 2023-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_assignattach1_action_action_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector_manager_action',
            name='action_creator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
