# Generated by Django 4.1.7 on 2023-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_sector_manager_action_action_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy_contract_action',
            name='action_file',
            field=models.FileField(default=0, upload_to='files'),
            preserve_default=False,
        ),
    ]
