# Generated by Django 4.1.7 on 2023-03-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_copy_contract_action_action_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_contract_action',
            name='action_file',
            field=models.FileField(default=0, upload_to='files'),
            preserve_default=False,
        ),
    ]
