# Generated by Django 4.1.7 on 2023-03-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_sector_manager_action_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector_manager_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
