# Generated by Django 4.1.7 on 2023-03-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_alter_sector_manager_action_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignattach1_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignattach2_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ceo_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='check_contract_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='check_data_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost_estimation_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='evp_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tcta_action',
            name='action_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
