# Generated by Django 4.1.7 on 2023-03-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_contract_detail_sgnlassign1_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlassign1_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlassign2_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlcheckContract_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlcopyContract_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
