# Generated by Django 4.1.7 on 2023-03-13 11:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0014_contract_detail_sgnlassign1_actionfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actions',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Action_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action_file',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='assignattach1_action',
            name='action_file',
            field=models.FileField(default='files/no_attachment.png', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='assignattach2_action',
            name='action_file',
            field=models.FileField(default='files/no_attachment.png', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='check_contract_action',
            name='action_file',
            field=models.FileField(default='files/no_attachment.png', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='association_contract',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='commercial_register',
            field=models.FileField(default='files/no_attachment.png', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='contract_quantities_table',
            field=models.FileField(default='files/no_attachment.png', upload_to='files', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='project_original_contract_quantities_table_copy',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlassign1_actionFile',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlassign2_actionFile',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlcheckContract_actionFile',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlcopyContract_actionFile',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='signature_authorization',
            field=models.FileField(default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sub_contractor_profile',
            field=models.FileField(blank=True, default='files/no_attachment.png', null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='zakat_Income_certificate',
            field=models.FileField(default='files/no_attachment.png', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action_file',
            field=models.FileField(default='files/no_attachment.png', upload_to='files'),
        ),
    ]
