# Generated by Django 4.1.7 on 2023-03-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_contractpermission_main_index'),
        ('contract', '0015_actions_is_read_actions_to_alter_actions_action_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Action_to', to='main.user_profile'),
        ),
    ]
