# Generated by Django 4.1.7 on 2023-03-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_actions_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='extra_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
