# Generated by Django 4.1.7 on 2023-03-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_alter_actions_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector_manager_action',
            name='action',
            field=models.CharField(choices=[('قبول', 'قبول'), ('رفض', 'رفض')], default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sector_manager_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail'),
        ),
    ]
