# Generated by Django 4.1.7 on 2023-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_alter_assignattach1_action_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
