# Generated by Django 4.1.7 on 2023-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_alter_copy_contract_action_action_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_contract_action',
            name='action_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
