# Generated by Django 4.1.7 on 2023-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_alter_check_contract_action_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignattach2_action',
            name='action_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
