# Generated by Django 4.1.7 on 2023-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_alter_assignattach2_action_action_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignattach1_action',
            name='action_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
