# Generated by Django 4.1.7 on 2023-03-15 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_alter_assignattach1_action_action_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='association_contract',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='commercial_register',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='contract_quantities_table',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='project_original_contract_quantities_table_copy',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='signature_authorization',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sub_contractor_profile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='zakat_Income_certificate',
            field=models.FileField(upload_to='files'),
        ),
    ]
