# Generated by Django 4.1.7 on 2023-03-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_alter_actions_action_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_contract_action',
            name='action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlceo_action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlcheckContract_action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlcostEstimation_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlevp_action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlfinancial_action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnllast_status_action',
            field=models.CharField(blank=True, default='اصدار جديد', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnllast_status_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnltcta_action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cost_estimation_action',
            name='action_file',
            field=models.FileField(default=0, upload_to='files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evp_action',
            name='action_note',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial_action',
            name='action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tcta_action',
            name='action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='check_contract_action',
            name='action',
            field=models.CharField(choices=[('قبول', 'قبول'), ('ملاحظات', 'ملاحظات'), ('تحديث مدير المناقصات', 'تحديث مدير المناقصات'), ('تحديث نائب الرئيس التنفيذي', 'تحديث نائب الرئيس التنفيذي'), ('تحديث الرئيس التنفيذي', 'تحديث الرئيس التنفيذي')], max_length=250),
        ),
        migrations.AlterField(
            model_name='check_contract_action',
            name='action_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='cost_estimation_action',
            name='action',
            field=models.CharField(choices=[('قبول', 'قبول'), ('تحديث', 'تحديث')], max_length=250),
        ),
        migrations.AlterField(
            model_name='financial_action',
            name='action',
            field=models.CharField(choices=[('قبول', 'قبول'), ('ملاحظات', 'ملاحظات')], max_length=250),
        ),
        migrations.AlterField(
            model_name='tcta_action',
            name='action',
            field=models.CharField(choices=[('قبول', 'قبول'), ('ملاحظات', 'ملاحظات')], max_length=250),
        ),
    ]
