# Generated by Django 4.1.7 on 2023-03-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_check_contract_action_action_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignmnt_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_creator', models.CharField(max_length=250)),
                ('action_date', models.DateTimeField(auto_now=True, null=True)),
                ('copy_contract_assign', models.CharField(choices=[('تم', 'تم')], max_length=250)),
                ('financial_assign', models.CharField(choices=[('تم', 'تم')], max_length=250)),
                ('check_contract_assign', models.CharField(choices=[('تم', 'تم')], max_length=250)),
                ('first_party_assign', models.CharField(choices=[('تم', 'تم')], max_length=250)),
                ('action_file', models.FileField(upload_to='files')),
            ],
            options={
                'verbose_name': 'AssignAttach2_action',
            },
        ),
        migrations.RemoveField(
            model_name='assignattach2_action',
            name='action_no',
        ),
        migrations.RenameField(
            model_name='contract_detail',
            old_name='sgnlassign2_action',
            new_name='check_contract_assign',
        ),
        migrations.RenameField(
            model_name='contract_detail',
            old_name='sgnlassign2_action_creator',
            new_name='copy_contract_assign',
        ),
        migrations.RenameField(
            model_name='contract_detail',
            old_name='sgnlassign2_actionFile',
            new_name='sgnlassignmnt_actionFile',
        ),
        migrations.RenameField(
            model_name='contract_detail',
            old_name='sgnlassign2_action_date',
            new_name='sgnlassignmnt_action_date',
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='financial_assign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='first_party_assign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='second_party_assign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlassignmnt_action_creator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='AssignAttach1_action',
        ),
        migrations.DeleteModel(
            name='AssignAttach2_action',
        ),
        migrations.AddField(
            model_name='assignmnt_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail'),
        ),
    ]
