# Generated by Django 4.1.7 on 2023-03-16 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0028_assignmnt_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmnt_action',
            options={'verbose_name': 'Assignmnt_action'},
        ),
    ]
