# Generated by Django 4.1.7 on 2023-03-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0030_alter_ceo_action_action_alter_evp_action_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceo_action',
            name='action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='evp_action',
            name='action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
