# Generated by Django 4.1.7 on 2023-03-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0031_ceo_action_action_note_alter_evp_action_action_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmnt_action',
            name='second_party_assign',
            field=models.CharField(choices=[('تم', 'تم')], default=0, max_length=250),
            preserve_default=False,
        ),
    ]
