# Generated by Django 4.1.7 on 2023-03-18 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_assignmnt_action_second_party_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='price_analysis',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='price_analysis_status',
            field=models.CharField(choices=[('مطلوب', 'مطلوب'), ('غير مطلوب', 'غير مطلوب')], default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmnt_action',
            name='action_file',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
