# Generated by Django 4.1.7 on 2023-03-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0033_contract_detail_price_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_des', models.CharField(blank=True, max_length=250, null=True)),
                ('template', models.FileField(upload_to='files')),
            ],
            options={
                'verbose_name': 'Contract_template',
            },
        ),
    ]
