# Generated by Django 4.1.7 on 2023-03-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0034_contract_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='sgnlsectorManager_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sector_manager_action',
            name='action_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='assignmnt_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignmnt_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='ceo_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CEO_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='check_contract_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Check_contract_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='check_data_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Check_data_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Copy_contract_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='cost_estimation_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cost_estimation_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='evp_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EVP_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='financial_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Financial_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='sector_manager_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sector_manager_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='tcta_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TCTA_action', to='contract.contract_detail'),
        ),
    ]
