# Generated by Django 4.1.7 on 2023-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0035_contract_detail_sgnlsectormanager_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action',
            field=models.CharField(choices=[('قبول', 'قبول'), ('تحديث', 'تحديث')], max_length=250),
        ),
    ]
