# Generated by Django 4.1.7 on 2023-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0036_alter_copy_contract_action_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmnt_action',
            name='contract_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='contract_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
