# Generated by Django 4.1.7 on 2023-03-19 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0038_rename_sgnlsectormanager_note_contract_detail_sgnlsectormanager_action_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action_file',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
