# Generated by Django 4.1.7 on 2023-03-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0039_alter_copy_contract_action_action_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmnt_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignmnt_action', to='contract.contract_detail', unique=True),
        ),
    ]
