# Generated by Django 4.1.7 on 2023-03-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0040_alter_assignmnt_action_action_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmnt_action',
            name='action_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignmnt_action', to='contract.contract_detail'),
        ),
        migrations.AlterField(
            model_name='assignmnt_action',
            name='contract_no',
            field=models.IntegerField(unique=True),
        ),
    ]
