# Generated by Django 4.1.7 on 2023-03-21 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0041_alter_assignmnt_action_action_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='assignmnt_action',
            name='action_file',
            field=models.FileField(upload_to='files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='check_contract_action',
            name='action_file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='association_contract',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='commercial_register',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='contract_quantities_table',
            field=models.FileField(upload_to='files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='price_analysis',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='project_original_contract_quantities_table_copy',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlassign1_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlassignmnt_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlcheckContract_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlcopyContract_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sgnlcostEstimation_actionFile',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='signature_authorization',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sub_contractor_profile',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='zakat_Income_certificate',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='copy_contract_action',
            name='action_file',
            field=models.FileField(upload_to='files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='cost_estimation_action',
            name='action_file',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
