# Generated by Django 4.1.7 on 2023-03-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0042_alter_actions_action_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='creator_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
