# Generated by Django 4.1.7 on 2023-03-28 11:30

import contract.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0044_actions_action_creator_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_code',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.IntegerField(default=contract.models.next_number)),
                ('request_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contract_detail')),
            ],
        ),
    ]
