# Generated by Django 4.1.7 on 2023-03-28 12:30

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0045_contract_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_code',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='contract_code',
            name='number',
            field=models.IntegerField(blank=True, default=contract.models.next_number, null=True),
        ),
    ]
