# Generated by Django 4.1.7 on 2023-03-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0047_contract_detail_contract_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_code',
            name='year',
            field=models.IntegerField(blank=True, default=2023, null=True),
        ),
    ]
