# Generated by Django 4.1.7 on 2023-03-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0048_alter_contract_code_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmnt_action',
            name='contract_no',
        ),
    ]
