# Generated by Django 4.1.7 on 2023-03-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0050_remove_contract_detail_sgnlassign1_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_creator', models.CharField(blank=True, max_length=250, null=True)),
                ('action_creator_name', models.CharField(blank=True, max_length=250, null=True)),
                ('action_date', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(blank=True, max_length=250, null=True)),
                ('action_note', models.CharField(blank=True, max_length=250, null=True)),
                ('action_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Actions_records', to='contract.contract_detail')),
            ],
            options={
                'verbose_name': 'Actions_records',
            },
        ),
    ]
