# Generated by Django 4.1.7 on 2023-03-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0051_actions_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions_records',
            name='action_file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
