# Generated by Django 4.1.1 on 2022-12-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('photo_tender', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
