# Generated by Django 4.1.1 on 2022-12-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tender_details',
            new_name='T_detail',
        ),
    ]
