# Generated by Django 4.1.1 on 2022-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0002_rename_tender_details_t_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_detail',
            options={'ordering': ['-no'], 'verbose_name': 'Tender'},
        ),
        migrations.AddField(
            model_name='t_detail',
            name='contract_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='documents_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='rfp_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='t_status',
            field=models.CharField(blank=True, choices=[('جارية', 'جارية'), ('تم التقديم', 'تم التقديم'), ('منتهية', 'منتهية'), ('ملغية', 'ملغية')], max_length=250, null=True),
        ),
    ]
