# Generated by Django 4.1.1 on 2022-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0003_alter_t_detail_options_t_detail_contract_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_detail',
            options={'ordering': ['no'], 'verbose_name': 'Tender'},
        ),
        migrations.AddField(
            model_name='t_detail',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
