# Generated by Django 4.1.1 on 2022-12-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0004_alter_t_detail_options_t_detail_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_detail',
            name='insurance_Required',
            field=models.CharField(blank=True, choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='management',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='owner',
            field=models.CharField(blank=True, choices=[('NEOM', 'NEOM'), ('الشركة للوطنية للاسكان', 'الشركة للوطنية للاسكان')], max_length=250, null=True),
        ),
    ]
