# Generated by Django 4.1.1 on 2023-01-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0005_t_detail_insurance_required_t_detail_management_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_detail',
            name='contract_duration',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='documents_value',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='insurance_Required',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='management',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='photo_author',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='photo_tender',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='rfp_no',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='submit_date',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='t_status',
        ),
        migrations.RemoveField(
            model_name='t_detail',
            name='title',
        ),
    ]
