# Generated by Django 4.1.1 on 2023-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0006_remove_t_detail_contract_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_detail',
            name='Bid_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='business_services_commencement_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='contract_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='documents_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='includes_supplyitems',
            field=models.CharField(blank=True, choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='initial_guarantee_required',
            field=models.CharField(blank=True, choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='insurance_Required',
            field=models.CharField(blank=True, choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='local_content_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='management',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='owner',
            field=models.CharField(blank=True, choices=[('NEOM', 'NEOM'), ('الشركة للوطنية للاسكان', 'الشركة للوطنية للاسكان')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='participation_confirmation_letter_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='photo_tender',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='receiving_inquiries_Deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='remaining_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='rfp_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='submitting_offers_method',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_detail',
            name='t_status',
            field=models.CharField(blank=True, choices=[('جارية', 'جارية'), ('تم التقديم', 'تم التقديم'), ('منتهية', 'منتهية'), ('ملغية', 'ملغية')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_detail',
            name='title',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
