# Generated by Django 4.1.1 on 2023-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0008_remove_t_detail_remaining_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_detail',
            name='rmnng_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='local_content_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='management',
            field=models.CharField(blank=True, choices=[('مباني', 'مباني'), ('بنية تحتية', 'بنية تحتية'), ('انشاءات', 'انشاءات')], max_length=250, null=True),
        ),
    ]
