# Generated by Django 4.1.1 on 2023-01-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0009_t_detail_rmnng_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_detail',
            name='rmnng_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
