# Generated by Django 4.1.1 on 2023-02-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0014_mngmnt_category_owner_list_required_tender_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='required1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='t_detail',
            name='initial_guarantee_required',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tendering.required1'),
        ),
    ]
