# Generated by Django 4.1.1 on 2023-02-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0015_required1_t_detail_initial_guarantee_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mngmnt_category',
            options={'verbose_name': 'Management'},
        ),
        migrations.AlterModelOptions(
            name='owner_list',
            options={'verbose_name': 'owner'},
        ),
        migrations.AlterModelOptions(
            name='required',
            options={'verbose_name': 'required'},
        ),
        migrations.AlterModelOptions(
            name='required1',
            options={'verbose_name': 'required1'},
        ),
        migrations.AlterModelOptions(
            name='tender_status',
            options={'verbose_name': 'tender_status'},
        ),
    ]
