# Generated by Django 4.1.1 on 2023-02-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0016_alter_mngmnt_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_detail',
            name='tt_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
