# Generated by Django 4.1.1 on 2023-02-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0018_remove_t_detail_tt_status_alter_t_detail_t_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_detail',
            name='tt_status',
            field=models.CharField(blank=True, default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tendering.tender_status'), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='t_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tendering.tender_status'),
        ),
    ]
