# Generated by Django 4.1.1 on 2023-02-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0021_delete_tender_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tender_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'tender_status',
            },
        ),
        migrations.AddField(
            model_name='t_detail',
            name='tt_status',
            field=models.CharField(blank=True, default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tendering.tender_status'), max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='t_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tendering.tender_status'),
        ),
    ]
