# Generated by Django 4.1.1 on 2023-02-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0023_remove_t_detail_tt_status_alter_t_detail_t_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_detail',
            name='rmnng_time',
        ),
    ]
