# Generated by Django 4.1.6 on 2023-02-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0024_remove_t_detail_rmnng_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_detail',
            name='submit_date',
            field=models.DateField(),
        ),
    ]
