# Generated by Django 4.1.6 on 2023-02-14 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tendering', '0026_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_user',
        ),
        migrations.AddField(
            model_name='task',
            name='task_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
