# Generated by Django 4.1.7 on 2023-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0029_alter_mngmnt_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_detail',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='rfp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
