# Generated by Django 4.1.7 on 2023-03-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0032_t_detail_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_detail',
            name='publication_date',
        ),
    ]
