# Generated by Django 4.1.7 on 2023-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0033_remove_t_detail_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_detail',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='initial_guarantee_required',
            field=models.CharField(blank=True, choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_detail',
            name='insurance_Required',
            field=models.CharField(blank=True, choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='required',
        ),
        migrations.DeleteModel(
            name='required1',
        ),
    ]
