# Generated by Django 4.1.7 on 2023-03-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0034_alter_t_detail_contract_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_detail',
            name='starting_date',
        ),
    ]
