# Generated by Django 4.1.7 on 2023-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0035_remove_t_detail_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_detail',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
