# Generated by Django 4.1.7 on 2023-03-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0037_t_detail_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_detail',
            name='publication_date',
        ),
    ]
