# Generated by Django 4.1.7 on 2023-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0038_remove_t_detail_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_detail',
            name='t_status',
            field=models.CharField(choices=[('جارية', 'جارية'), ('تم التقديم', 'تم التقديم'), ('منتهية', 'منتهية'), ('ملغية', 'ملغية')], default=0, max_length=250),
            preserve_default=False,
        ),
    ]
