# Generated by Django 4.1.6 on 2023-02-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('group1', models.CharField(blank=True, max_length=50, null=True)),
                ('group2', models.CharField(blank=True, max_length=50, null=True)),
                ('group3', models.CharField(blank=True, max_length=50, null=True)),
                ('group4', models.CharField(blank=True, max_length=50, null=True)),
                ('group5', models.CharField(blank=True, max_length=50, null=True)),
                ('group6', models.CharField(blank=True, max_length=50, null=True)),
                ('group7', models.CharField(blank=True, max_length=50, null=True)),
                ('group8', models.CharField(blank=True, max_length=50, null=True)),
                ('group9', models.CharField(blank=True, max_length=50, null=True)),
                ('group10', models.CharField(blank=True, max_length=50, null=True)),
                ('group11', models.CharField(blank=True, max_length=50, null=True)),
                ('group12', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
