# Generated by Django 4.1.6 on 2023-02-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='L_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'L_1',
            },
        ),
        migrations.CreateModel(
            name='L_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'L_2',
            },
        ),
        migrations.CreateModel(
            name='L_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'L_3',
            },
        ),
        migrations.CreateModel(
            name='L_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'L_4',
            },
        ),
        migrations.CreateModel(
            name='L_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'L_5',
            },
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'profile'},
        ),
        migrations.CreateModel(
            name='User_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.l_1')),
                ('l_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.l_2')),
                ('l_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.l_3')),
                ('l_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.l_4')),
                ('l_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.l_5')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
