# Generated by Django 4.1.6 on 2023-02-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_l_1_l_2_l_3_l_4_l_5_alter_user_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_level',
            options={'verbose_name': 'User_Level'},
        ),
        migrations.CreateModel(
            name='User_TenderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_app', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('add_new_tender', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('update_tender_detail', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('tender_detail', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('tender_report', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_TenderPermission',
            },
        ),
        migrations.CreateModel(
            name='User_ProjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_app', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('add_new_project', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('update_project_detail', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('project_detail', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('project_report', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_ProjectPermission',
            },
        ),
        migrations.CreateModel(
            name='User_ContractPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_app', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('add_new_contract', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('update_contract_step_1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('check_contract_step_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('cs_check_contract_step_3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('tcta_check_contract_step_4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('evp_check_contract_step_5', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('ceo_check_contract_step_6', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('print_contract_step_7', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('cs_check_contract_step_8', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('final_preview_contract_step_9', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('final_assignment_contract_step_10', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('contract_detail', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('contract_report', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_ContractPermission',
            },
        ),
    ]
