# Generated by Django 4.1.7 on 2023-03-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_level_options_user_tenderpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'ordering': ['user'], 'verbose_name': 'profile'},
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='group1',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='group10',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group11',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group12',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group2',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group3',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group4',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group5',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group6',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group7',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group8',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group9',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='project_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='sector_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
