# Generated by Django 4.1.7 on 2023-03-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_profile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='ceo_check_contract_step_6',
            new_name='AssignAttach1_action_12',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='check_contract_step_2',
            new_name='AssignAttach2_action_11',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='contract_detail',
            new_name='CEO_action_10',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='cs_check_contract_step_3',
            new_name='Check_contract_action_7',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='cs_check_contract_step_8',
            new_name='Check_data_action_3',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='evp_check_contract_step_5',
            new_name='Copy_contract_action_6',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='final_assignment_contract_step_10',
            new_name='Cost_estimation_action_4',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='final_preview_contract_step_9',
            new_name='EVP_action_9',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='print_contract_step_7',
            new_name='Financial_action_5',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='tcta_check_contract_step_4',
            new_name='Sector_manager_action_2',
        ),
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='update_contract_step_1',
            new_name='TCTA_action_8',
        ),
    ]
