# Generated by Django 4.1.7 on 2023-03-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_ceo_check_contract_step_6_user_contractpermission_assignattach1_action_12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='contract_report',
            new_name='user_index',
        ),
    ]
