# Generated by Django 4.1.7 on 2023-03-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_contract_report_user_contractpermission_user_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_contractpermission',
            old_name='user_index',
            new_name='project_index',
        ),
    ]
