# Generated by Django 4.1.7 on 2023-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_contractpermission_sector_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_contractpermission',
            name='main_index',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('NO', 'No')], max_length=250, null=True),
        ),
    ]
