# Generated by Django 4.1.7 on 2023-03-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_level',
            name='l_1',
        ),
        migrations.RemoveField(
            model_name='user_level',
            name='l_2',
        ),
        migrations.RemoveField(
            model_name='user_level',
            name='l_3',
        ),
        migrations.RemoveField(
            model_name='user_level',
            name='l_4',
        ),
        migrations.RemoveField(
            model_name='user_level',
            name='l_5',
        ),
        migrations.RemoveField(
            model_name='user_level',
            name='user',
        ),
        migrations.DeleteModel(
            name='L_1',
        ),
        migrations.DeleteModel(
            name='L_2',
        ),
        migrations.DeleteModel(
            name='L_3',
        ),
        migrations.DeleteModel(
            name='L_4',
        ),
        migrations.DeleteModel(
            name='L_5',
        ),
        migrations.DeleteModel(
            name='User_Level',
        ),
    ]
